### ISSUE TITLE
從新訓練model遇到問題

### ISSUE THREAD

**Issue by hongqingxie** [miemie2013/Keras-YOLOv4#13]
我在重新訓練model時遇到以下列問題：
在每5000步要eval集的mAP時遇到
Loading and preparing results...
Traceback (most recent call last):
  File "train.py", line 420, in <module>
    box_ap = eval(_decode, val_images, cfg.val_pre_path, cfg.val_path, cfg.eval_batch_size, _clsid2catid, cfg.draw_image)
  File "/home/Keras-YOLOv4/tools/cocotools.py", line 164, in eval
    box_ap_stats = bbox_eval(anno_file)
  File "/home/Keras-YOLOv4/tools/cocotools.py", line 92, in bbox_eval
    map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
  File "/home/Keras-YOLOv4/tools/cocotools.py", line 62, in cocoapi_eval
    coco_dt = coco_gt.loadRes(jsonfile)
  File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 326, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

請問有人有相同問題嗎？

**Comment by miemie2013** [comment]
> 我在重新訓練model時遇到以下列問題：
> 在每5000步要eval集的mAP時遇到
> Loading and preparing results...
> Traceback (most recent call last):
> File "train.py", line 420, in
> box_ap = eval(_decode, val_images, cfg.val_pre_path, cfg.val_path, cfg.eval_batch_size, _clsid2catid, cfg.draw_image)
> File "/home/Keras-YOLOv4/tools/cocotools.py", line 164, in eval
> box_ap_stats = bbox_eval(anno_file)
> File "/home/Keras-YOLOv4/tools/cocotools.py", line 92, in bbox_eval
> map_stats = cocoapi_eval(outfile, 'bbox', coco_gt=coco_gt)
> File "/home/Keras-YOLOv4/tools/cocotools.py", line 62, in cocoapi_eval
> coco_dt = coco_gt.loadRes(jsonfile)
> File "/usr/local/lib/python3.6/dist-packages/pycocotools/coco.py", line 326, in loadRes
> if 'caption' in anns[0]:
> IndexError: list index out of range
> 
> 請問有人有相同問題嗎？

是自定义数据集吗？可能json注解文件有问题。

**Comment by Y-ymmd** [comment]
您好，我想问一下您的问题解决了吗

**Comment by KaiHuangMO** [comment]
无它 模型崩了而  验证集过少或者训练数据太差
