### ISSUE TITLE
Error while trying to train a model for a new dataset

### ISSUE THREAD

**Issue by Merwanski** [miemie2013/Keras-YOLOv4#17]
Hey 

I am having the following error when I try to train a new model for the voc dataset!!!
Any idea how to solve this ?

Traceback (most recent call last):
  File "train.py", line 273, in <module>
    model_body.load_weights(cfg.model_path, by_name=True, skip_mismatch=True)
  File "........\.conda\envs\tflow_coco\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "........\.conda\envs\tflow_coco\lib\site-packages\keras\engine\network.py", line 1214, in load_weights
    reshape=reshape)
  File "........\.conda\envs\tflow_coco\lib\site-packages\keras\engine\saving.py", line 1245, in load_weights_from_hdf5_group_by_name
    g = f[name]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\merwan.birem\.conda\envs\tflow_coco\lib\site-packages\h5py\_hl\group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'tf_op_layer_split' doesn't exist)"

Thank you

Merwan

**Comment by miemie2013** [comment]
I havent seen this error before.Please install those packages in requirements.txt.

> Hey
> 
> I am having the following error when I try to train a new model for the voc dataset!!!
> Any idea how to solve this ?
> 
> Traceback (most recent call last):
> File "train.py", line 273, in
> model_body.load_weights(cfg.model_path, by_name=True, skip_mismatch=True)
> File ".........conda\envs\tflow_coco\lib\site-packages\keras\engine\saving.py", line 458, in load_wrapper
> return load_function(*args, **kwargs)
> File ".........conda\envs\tflow_coco\lib\site-packages\keras\engine\network.py", line 1214, in load_weights
> reshape=reshape)
> File ".........conda\envs\tflow_coco\lib\site-packages\keras\engine\saving.py", line 1245, in load_weights_from_hdf5_group_by_name
> g = f[name]
> File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "C:\Users\merwan.birem.conda\envs\tflow_coco\lib\site-packages\h5py_hl\group.py", line 264, in **getitem**
> oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
> File "h5py_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
> File "h5py_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
> File "h5py\h5o.pyx", line 190, in h5py.h5o.open
> KeyError: "Unable to open object (object 'tf_op_layer_split' doesn't exist)"
> 
> Thank you
> 
> Merwan

I havent seen this error before.Please install those packages in requirements.txt.

**Comment by Merwanski** [comment]
The packages were installed but still getting the same error

**Comment by Merwanski** [comment]
obsolete! no longer needed
