### ISSUE TITLE
请问是否可以将darknet-tiny-yolov4的weights文件转换成.h5？

### ISSUE THREAD

**Issue by B1D1ng** [miemie2013/Keras-YOLOv4#33]
我尝试执行convert.py转换darknet的yolov4-tiny weights，输出如下：
```
Weights Header:  0 2 5 [1280000]
Converting  0
Converting  1
Converting  2
Converting  3
Converting  4
Converting  5
Converting  6
Converting  7
Converting  8
Converting  9
Converting  10
Converting  11
Converting  12
Converting  13
Converting  14
Converting  15
Converting  16
Converting  17
Converting  18
Converting  19
Converting  20
Converting  21
Converting  22
Converting  23
Converting  24
Converting  25
Converting  26
Converting  27
Converting  28
Converting  29
Converting  30
Converting  31
Converting  32
Converting  33
Converting  34
Converting  35
Converting  36
Converting  37
Converting  38
Converting  39
Converting  40
Converting  41
Converting  42
Converting  43
Converting  44
Converting  45
Converting  46
Converting  47
Converting  48
Traceback (most recent call last):
  File "convert.py", line 173, in <module>
    yolo4_model = Yolo4(score, iou, anchors_path, classes_path, model_path, weights_path)
  File "convert.py", line 157, in __init__
    self.load_yolo()
  File "convert.py", line 130, in load_yolo
    buffer=weights_file.read(weights_size * 4))
TypeError: buffer is too small for requested array
```

**Comment by zongzong0408** [comment]
請問解決了嗎 ? 我也遇到同樣的問題。

**Comment by zongzong0408** [comment]
Hi，我利用這個資料庫可以成功轉檔。     
[keras-YOLOv3-model-set](https://github.com/david8862/keras-YOLOv3-model-set) 
你可以利用其中的 tools/model_converter/convert.py 去轉換 yolov4-tiny.weight -> yolov4-tiny.h5
