### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by china56321** [miemie2013/Keras-YOLOv4#7]
**博主好，yolov4.pt转keras,h5已转成功，现在检测其效果,当我运行demo.py时出现以下错误：**
Traceback (most recent call last):
  File "demo_fast.py", line 137, in <module>
    outs = yolo.predict(pimage)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
    callbacks=callbacks)
  File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
    batch_outs = f(ins_batch)
  File "/home/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/home/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/home/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/convolution}}]]
	 [[{{node lambda_1/Reshape_24}}]]

**请问这是怎么回事？怎么解决 ？**

**Comment by miemie2013** [comment]
> **博主好，yolov4.pt转keras,h5已转成功，现在检测其效果,当我运行demo.py时出现以下错误：**
> Traceback (most recent call last):
> File "demo_fast.py", line 137, in
> outs = yolo.predict(pimage)
> File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
> callbacks=callbacks)
> File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
> batch_outs = f(ins_batch)
> File "/home/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in **call**
> run_metadata=self.run_metadata)
> File "/home/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in **call**
> run_metadata_ptr)
> File "/home/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in **exit**
> c_api.TF_GetCode(self.status.status))
> tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> [[{{node conv2d_1/convolution}}]]
> [[{{node lambda_1/Reshape_24}}]]
> 
> **请问这是怎么回事？怎么解决 ？**

cuda版本要安装9，改天我写个readme或者升级一下tf为更新的版本支持cuda10吧！

**Comment by china56321** [comment]
> > **博主好，yolov4.pt转keras,h5已转成功，现在检测其效果,当我运行demo.py时出现以下错误：**
> > Traceback (most recent call last):
> > File "demo_fast.py", line 137, in
> > outs = yolo.predict(pimage)
> > File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training.py", line 1462, in predict
> > callbacks=callbacks)
> > File "/home/anaconda3/lib/python3.6/site-packages/keras/engine/training_arrays.py", line 324, in predict_loop
> > batch_outs = f(ins_batch)
> > File "/home/.local/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in **call**
> > run_metadata=self.run_metadata)
> > File "/home/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in **call**
> > run_metadata_ptr)
> > File "/home/.local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in **exit**
> > c_api.TF_GetCode(self.status.status))
> > tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
> > [[{{node conv2d_1/convolution}}]]
> > [[{{node lambda_1/Reshape_24}}]]
> > **请问这是怎么回事？怎么解决 ？**
> 
> cuda版本要安装9，改天我写个readme或者升级一下tf为更新的版本支持cuda10吧！

辛苦了
